version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - shared_data:/tmp

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile-celery
    depends_on:
      - redis
    volumes:
      - shared_data:/tmp

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"

volumes:
  shared_data:

