FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN apt update && apt install ffmpeg -y

WORKDIR /videocombiner-backend

COPY requirements.txt /videocombiner-backend/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /videocombiner-backend/

# Add a non-root user and set permissions
RUN useradd -ms /bin/sh myuser
USER myuser

ENTRYPOINT ["celery", "-A", "celery_app.app", "worker", "--loglevel=info", "-Q", "default"]
